[package]
name = "xando"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.android.activity_attributes]
"android:screenOrientation" = "userLandscape"

[dependencies]
macroquad="0.3.12"
